CREATE TABLE USER
(
    USER_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(16)  NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    UNIQUE KEY USERNAME (USERNAME)
);

CREATE TABLE ROLE
(
    ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    NAME    VARCHAR(45) NOT NULL
);

CREATE TABLE USER_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL
);

CREATE TABLE PRODUCT(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    BRAND VARCHAR(45) NOT NULL,
    MADEIN VARCHAR(45) NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    PRICE INT NOT NULL
);

ALTER TABLE USER_ROLES ADD FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE USER_ROLES ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);

