CREATE TABLE USER
(
    USER_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(16)  NOT NULL UNIQUE KEY,
    PASSWORD VARCHAR(250) NOT NULL
);

CREATE TABLE ROLE
(
    ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY ,
    NAME    VARCHAR(45) NOT NULL
);

CREATE TABLE USER_ROLES
(
    USER_ID BIGINT NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
    CONSTRAINT FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

