CREATE TABLE USER
(
    USER_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(16)  NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    ROLE  VARCHAR(16)  NOT NULL
);

-- CREATE TABLE ROLE
-- (
--     ROLE_ID  BIGINT AUTO_INCREMENT PRIMARY KEY,
--     ROLENAME VARCHAR(16)  NOT NULL
-- );
--
-- ALTER TABLE USER ADD FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID);


